make test pass but step on workflow will fail

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -18,5 +18,7 @@ jobs:
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test --no-build --verbosity normal
+    - name: Fail
+      run: echo "It will fail" && exit 1
     - name: Echo Something
       run: echo "Hey, you!"
